<?php

/**
 * @file
 * Primary module hooks for Solana Action module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function solana_action_theme($existing, $type, $theme, $path) {
  return [

    // field--user--field-sol-wallet--user.html.twig.
    'field__user__field_sol_wallet__user' => [
      'template' => 'field--user--field-sol-wallet--user',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_preprocess_field().
 */
function solana_action_preprocess_field__user__field_sol_wallet__user(&$variables, $hook) {

  // $wallet = $variables['element']['#items']->value;
  // Get user id of current user.
  $user = \Drupal::currentUser();
  $user_id = $user->id();

  // $domain = \Drupal::request()->getSchemeAndHttpHost();
  // $base_url = \Drupal::request()->getBaseUrl();
  $donate_link = Url::fromRoute('solana_action.user_donate', ['user_id' => $user_id], ['absolute' => TRUE])->toString();
  $donate_url = $donate_link;
  $variables['donate_url'] = $donate_url;
}
